# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:user;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;NON_KEYWORDS=USER
    username: root
    password: root
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
      schema-locations: classpath:/db/schema.sql
      continue-on-error: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always